Fix potential NPE when PKCE secret is missing
This prevents the following NPE from happening:

```java
java.lang.NullPointerException: Cannot invoke "String.length()" because "pkceSecret" is null
		at io.quarkus.oidc.runtime.TenantConfigContext.createPkceSecretKey(TenantConfigContext.java:50)
		at io.quarkus.oidc.runtime.TenantConfigContext.<init>(TenantConfigContext.java:42)
```