Runtime init `io.confluent.kafka.schemaregistry.avro.AvroSchemaUtils`
Depends on org.apache.avro.reflect.ReflectData$AllowNull since v7.4.5
which is runtime initialized resulting in:

```
Error: An object of type
'org.apache.avro.reflect.ReflectData$AllowNull' was found in the image
heap. This type, however, is marked for initialization at image run time
for the following reason: classes are initialized at run time by
default.
```

Closes: https://github.com/quarkusio/quarkus/issues/45742
(cherry picked from commit e4fbc9d104b747218fd3c5b0b78b9c935b16053f)