Fix regression in QuarkusDevModeTest
Since #55016 was merged, we had failures in
DevServicesKafkaContinuousTestingTest.testContinuousTestingDisablesDevServicesWhenPropertiesChange
:

java.lang.IllegalArgumentException: baseURI cannot be null
	at org.codehaus.groovy.vmplugin.v8.IndyInterface.fromCache(IndyInterface.java:344)
	at io.restassured.internal.common.assertion.AssertParameter.notNull(AssertParameter.groovy:26)
	at org.codehaus.groovy.vmplugin.v8.IndyInterface.fromCache(IndyInterface.java:344)
	at io.restassured.internal.RequestSpecificationImpl.<init>(RequestSpecificationImpl.groovy:135)
	at io.restassured.RestAssured.createTestSpecification(RestAssured.java:1453)
	at io.restassured.RestAssured.when(RestAssured.java:674)
	at io.quarkus.it.kafka.continuoustesting.DevServicesKafkaContinuousTestingTest.ping500(DevServicesKafkaContinuousTestingTest.java:144)

We need to be more careful when resetting the state.