Flyway callbacks can now access the Flyway instance
This prevents the following exception from happening when a Flyway Callback implementation attempts to access the Flyway object in Arc
(using `CDI.current().select(Flyway.class).get()`)

```
javax.enterprise.inject.CreationException: Synthetic bean instance for org.flywaydb.core.Flyway not initialized yet:
org_flywaydb_core_Flyway_3cb728d15a0a04006cc75d03f784feb2bba9a5fb
        - a synthetic bean initialized during RUNTIME_INIT must not be accessed during STATIC_INIT
        - RUNTIME_INIT build steps that require access to synthetic beans initialized during RUNTIME_INIT should consume the
SyntheticBeansRuntimeInitBuildItem
```

Add tests

(cherry picked from commit c09944508308391dafca34f3e7c4673ff744c115)