Fix generated getRequiredFeatures method for 22.3-dev
com.oracle.svm.reflect package moved in
22.3-dev (d727a0f9fdb6bc04a7445ed77a217ce4ced2d199) so we need to take
GraalVM version in account when generating
io.quarkus.runner.Feature#getRequiredFeatures to avoid
NoClassDefFoundError exceptions.