Exclude infinispan-server-runtime from Infinispan Client deployment
It brings the whole Infinispan and a ton of dependencies, including a
Kafka client dependency, which causes issues when using Micrometer as
the Kafka client is seen at deployment time (thus the Kafka Micrometer
bean is registered) and is not around at runtime leading to:
ClassNotFoundException: org.apache.kafka.clients.consumer.Consumer