Fix NPE when no library versions exist in the DevUI
Fixes the following exception:
```java
 java.lang.NullPointerException: Cannot invoke "java.util.List.iterator()" because the return value of "io.quarkus.devui.spi.page.CardPageBuildItem.getLibraryVersions()" is null
	at io.quarkus.devui.deployment.DevUIProcessor.addLibraryLinks(DevUIProcessor.java:967)
```

(cherry picked from commit 8ee28ab1efc6974c97a726a9272b09ed4012ebcc)