Tolerate failed cleanup causing
``````
Run git remote add quarkusio https://github.com/quarkusio/quarkus.git
error: remote quarkusio already exists.
Error: Process completed with exit code 3.
```