Recalculate compressed size in filterZipFile()
If the machine that produced the original JAR and the machine where
buildRunnerJar is running have different zlib versions, a

java.util.zip.ZipException: invalid entry compressed size (expected 1172 but got 1162 bytes)

may occur. Fix by forcing recalculation of compressed data size when
reusing a ZipEntry.

(cherry picked from commit fdf72f985bf3fa5bdb51de926cecbf5f0952090d)