Only substitute OctetKeyPair* classes when on the classpath
Under certain configurations (e.g. in
https://github.com/quarkusio/quarkus/issues/31930) the substitution
fails with:

```
Error: Substitution target for io.quarkus.smallrye.jwt.build.runtime.graalvm.Target_org_jose4j_jwk_OctetKeyPairJsonWebKey is not loaded. Use field `onlyWith` in the `TargetClass` annotation to make substitution only active when needed.
com.oracle.svm.core.util.UserError$UserException: Substitution target for io.quarkus.smallrye.jwt.build.runtime.graalvm.Target_org_jose4j_jwk_OctetKeyPairJsonWebKey is not loaded. Use field `onlyWith` in the `TargetClass` annotation to make substitution only active when needed.
```

which indicates that the class being substituted cannot be located on the classpath.

(cherry picked from commit 1b143e9660c9cac7e5d0a3f76e43f9e232c0e9f5)