Fixes Jackson serialization issues in native
com.fasterxml.jackson.databind.JsonMappingException: Class com.fasterxml.jackson.annotation.SimpleObjectIdResolver has no default (no arg) constructor
 at [Source: (io.quarkus.vertx.http.runtime.VertxInputStream); line: 1, column: 1]

com.fasterxml.jackson.databind.JsonMappingException: Class io.quarkus.registry.catalog.json.JsonArtifactCoordsDeserializer has no default (no arg) constructor
 at [Source: (io.quarkus.vertx.http.runtime.VertxInputStream); line: 1, column: 1]

(cherry picked from commit 1708ec6ae70360abb6c33791539f0717d1d4e973)