Allow Quarkus apps to build with 23.1
The bump in https://github.com/quarkusio/quarkus/pull/53661 results in
the following exception being thrown when building with Mandrel 23.1

```
java.lang.IllegalStateException: Out of date version of GraalVM or Mandrel detected: 23.1.11.0. Quarkus currently supports 25.0.0. Please upgrade to this version.
```

However, the intend of the PR was to print a warning like the following
instead of failing the build:

```
You are using an older version of GraalVM or Mandrel : 23.1.11.0. Quarkus currently supports 25.0.0. Please upgrade to this version.
```

Updating the docs to better reflect what the `MINUM` version is used for.