Add GraalVM 21.3 compatibility support for resource registration
oracle/graal#3774 changed the signature of ignoreResources as follows:

```
- public void ignoreResources(String pattern) {
+ public void ignoreResources(ConfigurationCondition condition, String pattern) {
```

This results in Quarkus throwing a `NoSuchMethodError` exception at the
code generated by NativeImageAutoFeatureStep

This patch looks for the right method based on the GraalVM/Mandrel version.

Closes: #20226
(cherry picked from commit b5361d8c2beb826be21d4f8e27b0df3ed4678b73)