@Scheduled "disabled" compilation error
Disabling a specific method with cron/every expression ("off" | "disabled") causes a build fail:

java.lang.IllegalStateException: Invalid cron()/every() expression: @Scheduled(every = "disabled") declared on ...

fixed by checking with SchedulerUtils.isOff(value) method.