Make `ValueRegistryParameterResolver` a bit more relaxed
We have seen this exception during the execution of some of our quarkus integration tests.

It seems that the `ValueRegistryParameterResolver` is called for types that are not "owned by it" and can cause the following exception.

Maybe the proposed change could help here.

```
org.junit.jupiter.api.extension.ParameterResolutionException: Could not retrieve parameter: org.apache.polaris.service.it.env.PolarisApiEndpoints arg0
	at io.quarkus.test.junit.ValueRegistryParameterResolver.getValueRegistry(ValueRegistryParameterResolver.java:46)
	at io.quarkus.test.junit.ValueRegistryParameterResolver.supportsParameter(ValueRegistryParameterResolver.java:25)
	at io.quarkus.test.junit.QuarkusIntegrationTestExtension.supportsParameter(QuarkusIntegrationTestExtension.java:367)
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:178)
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:179)
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1708)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:575)
	at java.util.stream.AbstractPipeline.evaluateToArrayNode(AbstractPipeline.java:260)
	at java.util.stream.ReferencePipeline.toArray(ReferencePipeline.java:616)
	at java.util.stream.ReferencePipeline.toArray(ReferencePipeline.java:622)
	at java.util.stream.ReferencePipeline.toList(ReferencePipeline.java:627)
	at java.util.ArrayList.forEach(ArrayList.java:1596)
```

(cherry picked from commit ba0b2cdefd85032261d1f68558ff469263cfdfce)