Disabling native image tests because of the following error
Fatal error: Failed to leave the current IsolateThread context and to detach the current thread. (code 12)