Make the creation of the Tracer bean lazy
This is needed to avoid a timing issue
that can lead to
java.lang.IllegalStateException: GlobalOpenTelemetry.set has already been called